### ISSUE TITLE
Requisitos básicos semana 01

### ISSUE THREAD

**Issue by PabloManoel** [PabloManoel/fornecedores_atletica#1]
### Mobile first 
- [x] #1: Criar modelo de itens da lista de busca
- [x] #2: Criar header 
- [x] #3: Criar sidebar menu lateral
- [x] #4: Criar botão de Filtros
- [x] #5: Criar pagina de detalhes do produto

**Comment by PabloManoel** [comment]
Afazeres Finalizados!
